# copy this file to /etc/ssh/sshd_config.d/
# See man 5 sshd_config

PermitRootLogin no
# Only allow pubickey authentification
AuthentificationMethod publickey

# Disable old protocols
Protocol 2

MaxAuthTries 6
MaxSessions 10
MaxStartups 10:50:80
