# copy this file to /etc/ssh/sshd_config.d/
# See man 5 sshd_config
# Check with validity `sudo /usr/sbin/sshd -t`

PermitRootLogin no
# Only allow pubickey authentification
AuthenticationMethods publickey

# Disable old protocols
Protocol 2

MaxAuthTries 6
MaxSessions 10
MaxStartups 10:30:80
