###################
##   BEHAVIOR    ##
###################
# Start new panes/window in current path
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Increase scrollback buffer
set -g history-limit 50000

# Enable mouse support
set -g mouse on
# Automaticaly copy selection to system clipboard
set -g set-clipboard on

# Aggressive resize for multi-client
setw -g aggressive-resize on

# Change prefix to Ctrl+a
# unbind C-b
# set -g prefix C-a
# bind C-a send-prefix

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Set terminal with proper colors
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Decorations
set -g status-right "#H  "
#set -g status-style "bg=red,fg=black"
#set -g pane-active-border-style "fg=red"

# Reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

###################
##      VI       ##
###################
# Fix Vim ESC delay (tmux 3.5+ already defaults to 10ms)
#set -sg escape-time 0

# Enable focus events for vim autoread
set -g focus-events on

# Use vi keys
setw -g mode-keys vi

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim-style pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
